# Generated by Django 4.0.2 on 2022-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='notes',
            field=models.TextField(default='no note'),
            preserve_default=False,
        ),
    ]
